version: '3.8'

services:
  web:
    image: prousername/crm:latest
    ports:
      - "8000:8000"
    command: sh -c "uvicorn app.main:app --reload --port=8000 --host=0.0.0.0"
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: crm
    volumes:
      - postgres_data:/var/lib/postgresql/data

  crm-front:
    image: prousername/crm-front:tagname
    ports:
      - "3000:80"
    depends_on:
      - web

volumes:
  postgres_data:
